apiVersion: batch/v1
kind: Job
metadata:
  name: caas-cmp-config-2
  namespace: caas-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    "helm.sh/hook": post-install,post-upgrade
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - command:
          - /bin/sh
          - -c
          - |-
            set -e
            echo "running cmp config....."
            sleep 10
            echo "adding my custom changes"
            echo "done....."
          image: "quay.io/helmpack/kubectl-helm-aws:0.1.1"
          imagePullPolicy: IfNotPresent
          name: caas-cmp-config
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      restartPolicy: Never
