apiVersion: batch/v1
kind: Job
metadata:
  name: caas-cmp-config
  namespace: caas-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    spec:
      containers:
        - command:
          - /bin/sh
          - -c
          - |-
            set -e
            echo "running cmp config....."
            sleep 10
            echo "adding my custom changes"
            sleep 20
            echo "done....."
          image: "quay.io/helmpack/kubectl-helm-aws:0.1.1"
          imagePullPolicy: IfNotPresent
          name: caas-cmp-config
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      restartPolicy: Never